server:
  port: 8080

spring:
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 200
  mail:
    host: smtp.163.com
    username: wmy0976543244@163.com
    password: NRZBAAMHADBMMHQJ
    protocol: smtp
    port: 25
    properties:
      mail:
        smtp:
          from: wmy0976543244@163.com
    default-encoding: utf-8

  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8

  redis:
    host: 121.41.45.164
    port: 6379
    database: 0
    password: 123123
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

  datasource:
      url: jdbc:mysql://121.41.45.164:3306/onlinetest?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: wmy0976543244
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mybatis/*.xml

TencentCos:
  secretId: AKID0xoU5b7bUEl6Tnz55xdAWelhR1WqyINO
  secretKey: DG5qR9j6OYaS6XkiT4Z2OYilpplgYIwP
  bucketName: picture-1317807251
  region: ap-shanghai



